 

import { PERMISSIONS, SYSTEM_ROLE_PERMISSIONS as CORE_SYSTEM_ROLE_PERMISSIONS } from '@atlas/core';

export const REPUTATION_PERMISSIONS = {
  VIEW: PERMISSIONS.reputation.view,
  MANAGE: PERMISSIONS.reputation.manage,
  SETTINGS_MANAGE: PERMISSIONS.reputation.settingsManage,
  REQUEST_CREATE: PERMISSIONS.reputation.requestCreate,
  FEEDBACK_VIEW: PERMISSIONS.reputation.feedbackView,
  // Reputation V2 Permissions
  CAMPAIGN_CREATE: 'reputation.campaign_create',
  CAMPAIGN_UPDATE: 'reputation.campaign_update',
  CAMPAIGN_ARCHIVE: 'reputation.campaign_archive',
  FEEDBACK_ASSIGN: 'reputation.feedback_assign',
  FEEDBACK_RESOLVE: 'reputation.feedback_resolve',
  NOTES_MANAGE: 'reputation.notes_manage',
  ANALYTICS_VIEW: 'reputation.analytics_view'
} as const;

const NEW_REPUTATION_PERMISSIONS = [
  REPUTATION_PERMISSIONS.CAMPAIGN_CREATE,
  REPUTATION_PERMISSIONS.CAMPAIGN_UPDATE,
  REPUTATION_PERMISSIONS.CAMPAIGN_ARCHIVE,
  REPUTATION_PERMISSIONS.FEEDBACK_ASSIGN,
  REPUTATION_PERMISSIONS.FEEDBACK_RESOLVE,
  REPUTATION_PERMISSIONS.NOTES_MANAGE,
  REPUTATION_PERMISSIONS.ANALYTICS_VIEW
];

export const SYSTEM_ROLE_PERMISSIONS = {
  ...CORE_SYSTEM_ROLE_PERMISSIONS,
  OWNER: [...CORE_SYSTEM_ROLE_PERMISSIONS.OWNER, ...NEW_REPUTATION_PERMISSIONS],
  ADMIN: [...CORE_SYSTEM_ROLE_PERMISSIONS.ADMIN, ...NEW_REPUTATION_PERMISSIONS],
  MEMBER: [...CORE_SYSTEM_ROLE_PERMISSIONS.MEMBER, REPUTATION_PERMISSIONS.ANALYTICS_VIEW],
};
